dist: xenial
sudo: false

language: node_js
node_js:
  - "10.9"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

script:
  - npm run-script build
  - cd dist/angular-github-pages-travis
  - cp index.html 404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/expenses-manager-client
  on:
    branch: setup-pages-deploy
